### ISSUE TITLE
publish on npm

### ISSUE THREAD

**Issue by piranna** [lite20/PalmTree#1]
Finally I got time to review and improve it and work like a charm in NodeOS :-) Would you be able to publish a new version on npm?

**Comment by mitsukaki** [comment]
Will do!

**Comment by piranna** [comment]
Perfect ;-) We should consider about doing some unit tests, it's a simple
program but it would not make any hurt... :-P

**Comment by mitsukaki** [comment]
I just updated the module. I'll write some mocha tests when I get on my laptop

**Comment by piranna** [comment]
Cool :-)

**Comment by mitsukaki** [comment]
@piranna I had to 'modulify" PalmTree to make tests work but PalmTree works beautifully. Awaiting nodejs integration.

I should forwarn you, it doesn't reboot applications that close (if you intended for it to do that, it doesn't). Because we spawn everything detached, the program simply terminates when done launching. I hope that was your intended behaviour, else I can adjust it.

I've published the newest version as 2.5.0 on npm.

**Comment by piranna** [comment]
> @piranna I had to 'modulify" PalmTree to make tests work but PalmTree
> works beautifully.

Have you put some fragments on an inportable module? Good idea :-)

> Awaiting nodejs integration.

Do you mean NodeOS? It's working flawlesly there :-) I'll wait until I have
working the rewritten nsh (I'm having problems with the stdio streams...)
before upload my changes to NodeOS.

> I should forwarn you, it doesn't reboot applications that close (if you
> intended for it to do that, it doesn't). Because we spawn everything
> detached, the program simply terminates when done launching. I hope that
> was your intended behaviour, else I can adjust it.

Detached is not the problem, but do I have an .unref() somewhere? This
makes parent process to don't wait child one to finish, the same way you
are describing. Probably my fault, I'm used to use it. Please fix it,
process should be restarted.

> I've published the newest version as 2.5.0 on npm.

Ok :-)

**Comment by mitsukaki** [comment]
> .unref() 

I was curious as to why you added that haha yes I'll remove it and test again. Mind if I take a peek at NSH to see if I can give you a hand?

**Comment by mitsukaki** [comment]
> Do you mean NodeOS? 

Woops! Yeah haha

**Comment by piranna** [comment]
> Mind if I take a peek at NSH to see if I can give you a hand?

I'll upload a new version, but seems to be a dificult bug, launched
programs are loosing keystrokes without reason... :-/
