### ISSUE TITLE
npm collaborator

### ISSUE THREAD

**Issue by piranna** [lite20/PalmTree#3]
Could you be able to give me permissions to publish on `npm`? I want to publish a new version with latests changes...

Also, do you mind if we move this to the `NodeOS` organization?

**Comment by piranna** [comment]
I would like to publish master as 2.6.0, you could do it too if you want.

**Comment by mitsukaki** [comment]
Sure I can give you permission and we could definitely move it. I'll get to
that

**Comment by mitsukaki** [comment]
@piranna completed! You can go ahead and publish it! Now, to move it to NodeOS?

**Comment by mitsukaki** [comment]
Complete! Enjoy!

**Comment by piranna** [comment]
Cool, thanks! :-D I'm going to wait if I get some response on https://github.com/docker/docker/issues/31078 before publishing it, maybe my latest change is not needed :-)
